[package]
name = "stdmath"
version = "0.1.0"
authors = ["Miraclx <omiraculous@gmail.com>"]
edition = "2018"

[dependencies]
rayon = {version = "1.4.0", optional = true}

[features]
cache = []
concurrency = ["rayon"]
